// <auto-generated />
using System;
using BurgerShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240814092648_newDatabaseSetup")]
    partial class newDatabaseSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BurgerShop.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BasePrice")
                        .HasColumnType("int");

                    b.Property<string>("BurgerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePrice = 100,
                            BurgerName = "Crispy Supreme",
                            Description = "A serving of the Crispy Chicken Supreme Burger from Betty’s Burgers clocks in at a hearty 865 calories. That’s quite a culinary adventure! 🌟",
                            ImageUrl = "~/images/burger_image.png"
                        },
                        new
                        {
                            Id = 2,
                            BasePrice = 100,
                            BurgerName = "Surprise",
                            Description = "The legendary surprise burger—a delightful concoction that combines nostalgia, creativity, and a touch of culinary magic! 🍔✨",
                            ImageUrl = "~/images/burger_image.png"
                        },
                        new
                        {
                            Id = 3,
                            BasePrice = 100,
                            BurgerName = "Whopper",
                            Description = "The Whopper—a legendary burger that has graced fast-food menus since 1957. 🍔",
                            ImageUrl = "~/images/burger_image.png"
                        },
                        new
                        {
                            Id = 4,
                            BasePrice = 100,
                            BurgerName = "Chilli Cheese",
                            Description = "The world of Chili Cheese Burgers—a delightful fusion of juicy burgers, melty cheese, and a kick of chili goodness. 🍔🌶️",
                            ImageUrl = "~/images/burger_image.png"
                        },
                        new
                        {
                            Id = 5,
                            BasePrice = 100,
                            BurgerName = "Tandoor Grill",
                            Description = "The flavorful world of Tandoori Chicken Burgers—a delightful twist on traditional burgers that brings together bold spices, juicy chicken, and a touch of South Asian flair. 🍔🌶️",
                            ImageUrl = "~/images/burger_image.png"
                        });
                });

            modelBuilder.Entity("BurgerShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BurgerCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BurgerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BurgerShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BurgerShop.Models.Order", b =>
                {
                    b.HasOne("BurgerShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
