// <auto-generated />
using System;
using BurgerShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BurgerShop.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240726171452_AddUserAndOrderTableToDb")]
    partial class AddUserAndOrderTableToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BurgerShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BurgerCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BurgerType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            BurgerCategory = "Veg",
                            BurgerType = "Crispy Burger",
                            Price = 100m,
                            Quantity = 2,
                            TotalPrice = 200m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            BurgerCategory = "Non-Veg",
                            BurgerType = "Tandoor Grill",
                            Price = 200m,
                            Quantity = 1,
                            TotalPrice = 200m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            BurgerCategory = "Veg",
                            BurgerType = "Whopper",
                            Price = 100m,
                            Quantity = 1,
                            TotalPrice = 100m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("BurgerShop.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MobileNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MobileNo = "1234567890"
                        },
                        new
                        {
                            Id = 2,
                            MobileNo = "9876543210"
                        });
                });

            modelBuilder.Entity("BurgerShop.Models.Order", b =>
                {
                    b.HasOne("BurgerShop.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
